# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('datetime_lastmodified', models.DateTimeField(auto_now=True)),
                ('recommended_start_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recommended_end_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recommended_ratio', models.DecimalField(decimal_places=3, max_digits=4)),
                ('sound_file', models.ImageField(default='media/tracks/none.wav', upload_to='media/tracks/')),
            ],
        ),
    ]
