# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsgonnarain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='sound_file',
            field=models.FileField(default='tracks/none.wav', upload_to='tracks/'),
        ),
    ]
